version: '3.8'

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_management
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3307:3306"  # Change host port to 3307
    networks:
      - app-network

  studentmanagement-app:
    build: .
    container_name: studentmanagement-app
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
